language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: T4wDCP5ZmORo/9dh5PTsw0VhRNeNfTiGJAsRY4WIAMVXHyT5snItRJdauadidsjDXnBHncaEftm3eByf3A2YXEnbCYIAoevHXBRORLXTY1cQvMFlJtC/9d22jyy3asEkE1/5TJkolfnyX4b0so4n/t9dsxOEynRfvx4tKB9RChpjyQ4Dd0IHu+goocSlYudhqMOJ4fKu7CiUlsfjcjQt7+5bKOQg8xbYA+52Ajv/Q5hAvK9rcQrHw1i1E8xnkKvdlKdXoLbzHXItw45ZSqlx8F0HyApuyKI4v9NAqns0d5zePWi90/E8Th/sYnCzfnJ5htV+MHQMi1GG6HaJ9sDhl695Amh9VNmPjjOU+J816qy40Jfnjb1gk0if6VPC7D5CP32MisJ23oX+w+M/BLuC/8G5NX+BYDf7T9ZT3vwggomg/Yz7UjXIGqPIXc/rgpRj8IIAkJVBAxc2sz1mgglDQHf5elUVMlkfFwESgcUEom/CJl70XUbFFnRYvIWNpoedtOuIxBs92LsWv+lvPf2aktSZoceKfWGJ9tv3VAK9JuiH6Us+PYTnxJgvylrtVTAdkpjMF1C9l6ChBV7XoW3dLPSg/a0klIg61moZqOPk3AnzV8hoyturnTtD97F224DK28ROMFdz0xIJPyHUs1hvmlnU/x8/3BNJQCjp3jNUGWU=
  app: ican2app
